console.log("Recipe Details");
console.log("---------------");
var recipeName="creamy squash linguine";
var preparationTime=45;
var recipeBy="Jimmy Cutter";
var isVegetarian=true;
var calories=223.7;
console.log("Recipe Name: "+recipeName);
console.log("Preparation Time: "+preparationTime);
console.log("Recipe By: "+recipeBy);
console.log("Is Vegetarian: "+isVegetarian);
console.log("Calories: "+calories);
console.log("Recipe Deatils after Update");
console.log("-----------------------------");
var recipeName="creamy squash linguine";
var preparationTime=60;
var recipeBy="Jimmy Cutter George";
var isVegetarian=true;
var calories=223.7;
console.log("Recipe Name: "+recipeName);
console.log("Preparation Time: "+preparationTime);
console.log("Recipe By: "+recipeBy);
console.log("Is Vegetarian: "+isVegetarian);
console.log("Calories: "+calories);